Job fail on alloc failed
SpiNNakerManchester/JavaSpiNNaker pull request #1135
Opened 2024-02-26 13:34 UTC by rowleya

Adds option to remove job queue altogether

2024-02-27 10:28 UTC, Christian-B requested changes

2024-02-27 10:28 UTC, Christian-B commented on SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/AllocatorTask.java
> -					sql.delete.call(task.id);
I think you still need this line as otherwise the job stays in requested forever

2024-02-27 10:28 UTC, Christian-B commented on SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/AllocatorTask.java
> +						&& allocProps.isFailJobOnFailAllocation()) {
Longer term this needs to be fancier but ok for now

2024-02-27 12:21 UTC, rowleya commented on SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/AllocatorTask.java
> -					sql.delete.call(task.id);
I think this was an error introduced previously.  I thought that we needed to remove the job queue item when it was allocated but actually a lot of things can still go wrong between a job being allocated and a job being ready meaning that you need to leave it on the queue.  Note that the job queue table is not the same as the job queue.  The job queue is the combination of job entries and job queue entries that are in the queued state; once allocated a job goes into powering, which is either successful so it goes to ready, or fails, so it goes back in the queue...

2024-02-27 12:22 UTC, rowleya commented on SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/AllocatorTask.java
> +						&& allocProps.isFailJobOnFailAllocation()) {
We can make this fancier now; the failure or otherwise of a job can be more fine grained if desired and then allow for better queuing...

2024-02-27 15:14 UTC, Christian-B commented on SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/AllocatorTask.java
> -					sql.delete.call(task.id);
Yes I see how src/main/resources/queries/get_allocation_tasks.sql can handle things staying in the job_request table forever.

If however we want to switch to keeping the job permanently in both the jobs and job_request tables it raises the question of should this be two tables or just one as there will now be a permanent  one to one mapping between the two tables.

2024-02-27 15:58 UTC, Christian-B commented on SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/AllocatorTask.java
> -					sql.delete.call(task.id);
Not calling sql.delete.call(task.id) will help with a job where the allocation fails temporarily as stated.
This avoids the danger of that single job remaining status QUEUE forever

But if whatever caused the allocation to fail will happen very time the task will increase in importance until it blocks the Queue for all other tasks!

So then it becaomes a choise of which evil is preferred.

2024-02-27 16:38 UTC, Christian-B commented
Approved to merge Assuming this passed all tests.

In a follow up pr we can look at which jobs to keep in the queue if no boards available.

2024-02-27 16:40 UTC, Christian-B approved these changes
my comments remain but are not blockers

2025-07-08 17:46 UTC, rowleya commented
This has been done elsewhere now.

2025-07-08 17:46 UTC, closed without merging