Spalloc server
SpiNNakerManchester/JavaSpiNNaker pull request #664
Opened 2022-12-01 13:51 UTC by rowleya

General fixes that make the spalloc client end work, as well as actual use of spalloc proxies in the Front End code.

2022-12-05 09:59 UTC, dkfellows commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/Transceiver.java
> +		// Avoid delegation of the process if not needed
It seems to me like this ought to be something that gets wrapped into `simpleProcess()` or at least into a helper method.

2022-12-05 10:28 UTC, dkfellows requested changes
A few things I'm a touch concerned about.

2022-12-05 10:28 UTC, dkfellows commented on SpiNNaker-storage/src/main/java/uk/ac/manchester/spinnaker/storage/ProxyInformation.java
> +public class ProxyInformation {
The validity definitions in this class need to change. `@Valid` says "use the validity rules from the class of thing it is" and `String` doesn't have any as it is a built-in class.

I'd guess that `@NotBlank` would be a good start; tmpty strings are definitely not going to work.

2022-12-05 10:28 UTC, dkfellows commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/SpallocClientFactory.java
> +	private static final Map<String, Machine> MACHINE_MAP =
Formally, this could get into trouble if you were writing code that talks to multiple spalloc servers at once where those have machines with the same name. It's not a scenario that I think is going to be very worrying for anyone other than ourselves.

2022-12-05 10:28 UTC, dkfellows commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/ClientSession.java
> +		// If we didn't use a bearer token, we need to log in properly
With a bearer token, is the initial session authorized then? I was wondering about that. What we don't want to do is to send the bearer token every time, since that forces a (slow) roundtrip to keycloak on every service call.

2022-12-05 10:28 UTC, dkfellows commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/ClientSession.java
> +		var setCookie = conn.getHeaderField(SET_COOKIE);
I didn't use this method because there can be *multiple* `Set-Cookie` headers in a response (it's one per cookie being set *or deleted* &mdash; I know that's not formally part of the spec but it damn well exists in practice!) and I can't be certain that there aren't more than one or what order they are.  The javadoc string for the one you're using says:

     * Returns the value of the named header field.
     * <p>
     * If called on a connection that sets the same header multiple times
     * with possibly different values, only the last value is returned.

So yes, it'd make the code neat if we could use it, and conceptually it's what we're doing, but I suspect we can't do so safely.

2022-12-05 10:28 UTC, dkfellows commented on SpiNNaker-storage/src/main/java/uk/ac/manchester/spinnaker/storage/sqlite/SQLiteProxyInformation.java
> +		try (var s = conn.prepareStatement(GET_PROXY_INFORMATION)) {
This line can be combined with the next one, and try-with-resources will do the Right Thing&trade;. It's neat that works.

2022-12-05 13:40 UTC, rowleya commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/transceiver/Transceiver.java
> +		// Avoid delegation of the process if not needed
Fixed.

2022-12-05 13:41 UTC, rowleya commented on SpiNNaker-storage/src/main/java/uk/ac/manchester/spinnaker/storage/ProxyInformation.java
> +public class ProxyInformation {
Sorry didn't look at this in great detail!  Added notempty for now...

2022-12-05 13:41 UTC, rowleya commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/SpallocClientFactory.java
> +	private static final Map<String, Machine> MACHINE_MAP =
I am not overly concerned with this!

2022-12-05 13:41 UTC, rowleya commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/ClientSession.java
> +		// If we didn't use a bearer token, we need to log in properly
Yes the initial session seems to be authorized once the bearer is used.  It still gets the cookie here so it seems to work...

2022-12-05 13:41 UTC, rowleya commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/ClientSession.java
> +		var setCookie = conn.getHeaderField(SET_COOKIE);
Oh yes... it wasn't working as it was, but I have updated it now so it should work...

2022-12-05 13:41 UTC, rowleya commented on SpiNNaker-storage/src/main/java/uk/ac/manchester/spinnaker/storage/sqlite/SQLiteProxyInformation.java
> +		try (var s = conn.prepareStatement(GET_PROXY_INFORMATION)) {
Ah yes... I know about these things, just that they don't fit into my current way of thinking!  Fixed now.

2022-12-12 09:01 UTC, dkfellows approved these changes

2022-12-15 16:28 UTC, dkfellows commented on SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/Spalloc.java
> +		return executeRead(c -> getMachines(c, allowOutOfService));
This was another wrong (over-locked) transaction type.

2022-12-15 16:30 UTC, dkfellows commented on SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/bmp/BMPController.java
> +	private final Set<Integer> busyJobs = new ConcurrentSkipListSet<>();
This is kept only in memory because restarting the server invalidates any information that it might have.

2022-12-15 16:31 UTC, dkfellows commented on SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/DatabaseAwareBean.java
> +		public final <T> T transactionRead(TransactedWithResult<T> action) {
Less error prone to do it like this.

2022-12-15 16:32 UTC, dkfellows commented on SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/Utils.java
> +	public static boolean isBusy(SQLException exception) {
Because writing this `switch` several times gets old...

2022-12-15 16:38 UTC, dkfellows commented on SpiNNaker-front-end/src/main/java/uk/ac/manchester/spinnaker/front_end/dse/ThrottledConnection.java
> +			connection = new SCPConnection(location,
Future TODO: get the transceiver to manufacture the connection? That would let it hide whether it is using the proxy, and also the transceiver already knows the machine layout. Hmm.

Not worth holding back this PR.

2022-12-15 17:41 UTC, merged