Spalloc server jdbc
SpiNNakerManchester/JavaSpiNNaker pull request #737
Opened 2023-02-20 10:37 UTC by rowleya

Changes that make the Spalloc Server work with MySQL via JDBC.  A few notes:
 - The "historical database" is now a fully separate database; the main connection cannot access it, so there are now queries that read from the main database and write to the historical database
 - A lot of the changes here were from returning a MappableIterable<T> from a query to embedding the code that reads the row into the query as an Interface / lambda call and returning instead a List<T>.  If more work needs to be done, this list is then streamed again afterwards using a wrapper lambda (Row.stream), and is thus a bit less memory-efficient (though in testing the memory was not an issue at all).
 - Most of the queries have been changed to work with MySQL.  I therefore removed the SQLiteImplementation.  To do anything that would let both run would be much more complex.
 - Testing relies on the TestContainers library, which runs mysql in a docker instance.  You need to install docker and be able to run docker commands as the user running the tests (this happens automatically on github apparently).

IntegrationTests:
 - Without spalloc server interaction (to prove main code will still work): http://apollo.cs.man.ac.uk:8080/blue/organizations/jenkins/Integration%20Tests/detail/spalloc-server-jdbc/41/
 - With spalloc server interaction but no proxy use (failure appears to be due to random hardware issue): http://apollo.cs.man.ac.uk:8080/blue/organizations/jenkins/Integration%20Tests/detail/spalloc-server-jdbc/42/
 - With spalloc server interaction with proxy use (failure looks like random hardware or network issue): http://apollo.cs.man.ac.uk:8080/blue/organizations/jenkins/Integration%20Tests/detail/spalloc-server-jdbc/43/

2023-02-20 12:20 UTC, dkfellows commented
Even in the old code, rows were not things that should have ever left a transaction context (as rows were designed to go Boom! if ever accessed after the transaction was closed). Every query could have been thought of as producing 0 rows of result (most inserts and updates), 1 row of result (where I'd set a `LIMIT`), or a sequence of rows; these corresponded to the types `int`/`void`, `Optional<Row>`, and `MappableIterable<Row>`. (They didn't quite comfortably fit the model of `Stream<Row>`. I forget why.)

2023-02-20 12:27 UTC, dkfellows commented on SpiNNaker-allocserv/pom.xml
> +			<dependency>
I recommend (but *not* strongly) that all dependency version management be put in the parent POM if possible. This isn't something to block this PR; it can be fixed later.

2023-02-20 12:54 UTC, rowleya commented
> Even in the old code, rows were not things that should have ever left a transaction context (as rows were designed to go Boom! if ever accessed after the transaction was closed). Every query could have been thought of as producing 0 rows of result (most inserts and updates), 1 row of result (where I'd set a LIMIT), or a sequence of rows; these corresponded to the types int/void, Optional<Row>, and MappableIterable<Row>. (They didn't quite comfortably fit the model of Stream<Row>. I forget why.)

> However, concrete types have to be used once you cross a transaction boundary. In particular, that means that I would convert MappableIterable<Row> usually into List<Thing> or Set<Thing> or Map<Key,Thing>.

This was true in the old code, but in JdbcTemplate you aren't even allowed out of the method call!  There are ways to get a closed ResultSet-like thing out of there, but this thing is essentially a full copy of the ResultSet which then also doesn't let you get at Blobs (for good reason).  The solution taken here is simply to move deeper inside the call so the full extraction can be done before you leave.  The downside is that I guess it ends up making the copy, though at least not as deep...  

In testing, I did look at the memory use of the server, and it was generally very low overall, so I don't expect issues with this because of that change.

2023-02-20 12:55 UTC, rowleya commented
I should add that in many cases the list is made anyway so it didn't have that big an impact.

2023-02-20 16:17 UTC, dkfellows requested changes
I'm not convinced that things are right.

And you should probably add a connection pool.

2023-02-20 16:17 UTC, dkfellows commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/SpallocClientFactory.java
> -			conns.add(new ProxiedBootConnection(ws));
No boot connection? That makes this proxy only a partial proxy; it can't bring up a newly allocated set of boards.

2023-02-20 16:17 UTC, dkfellows commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/SCPConnection.java
> +	public SCPConnection(HasChipLocation chip, InetAddress localHost,
Why add in `localHost` and `localPort`? Nobody and nothing specifies them as anything other than `null, null`.

2023-02-20 16:22 UTC, dkfellows commented
I'm particularly concerned that the query used when allocating a rectangle rooted at a particular chip might be wrong. It really doesn't need the general machine-wide grid; it knows where it wants to start (which had better be with Z=0, but that's enforced elsewhere).

2023-02-21 13:23 UTC, rowleya commented on SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/compat/Command.java
> +		this.args = new ArrayList<Object>(args);
It appears null *does* need to be supported... when I tried this with "normal" old spalloc, it crashed here because of null values.

2023-02-21 13:26 UTC, rowleya commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/SpallocClient.java
> -		EIEIOConnection getEIEIOConnection()
I think this was something I was about to find a complicated way to change, then realised that it isn't used.  It could also be added back in when needed in future...

2023-02-21 13:28 UTC, rowleya commented on SpiNNaker-allocserv/src/main/resources/queries/get_reported_boards.sql
> +	WHERE boards.functioning != 0 -- Ignore disabled boards
I can't think why it would be NULL.  I think MySQL doesn't like "is not" though.

2023-02-21 13:32 UTC, rowleya commented on SpiNNaker-allocserv/src/main/resources/queries/get_reported_boards.sql
> +	WHERE boards.functioning != 0 -- Ignore disabled boards
I note that elsewhere in the code it can "setFunctioning" and that takes a boolean i.e. cannot be NULL.

2023-02-21 13:32 UTC, rowleya commented on SpiNNaker-allocserv/src/main/resources/queries/find_rectangle_at.sql
> +	gx(x) AS (SELECT 0 UNION ALL SELECT x+1 FROM gx, m
This appeared to be an old copy of the statement.  It has now been updated to match the new one.

2023-02-21 13:36 UTC, rowleya commented on SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/web/SystemControllerImpl.java
> +	@PreAuthorize(IS_READER)
Oops!  Fixed.

2023-02-21 13:37 UTC, rowleya commented on SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/web/SystemController.java
> +	@PreAuthorize(IS_READER)
Fixed here too.

2023-02-21 13:41 UTC, rowleya commented on SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/DatabaseEngineJDBCImpl.java
> +		return resolved;
Yes, true.  Done.

2023-02-21 13:46 UTC, rowleya commented on SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/DatabaseAPI.java
> +	interface RowMapper<T> {
It is now a FunctionalInterface.  Not sure this differs much from previous patterns used otherwise (e.g. ConnectedWithResult etc.).

2023-02-21 13:46 UTC, rowleya commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/SpallocClient.java
> +				uk.ac.manchester.spinnaker.machine.Machine machine)
Arguably yes, but then we pass the Machine into Java before this is called, so why read it again?

2023-02-21 13:47 UTC, rowleya commented on SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/db/DQLTest.java
> -			assertEquals(Set.of("job_id", "machine_id", "machine_name", "width",
We would need to do something seriously more than this to make it work in the JDBC world.  You just don't have access to this sort of information at any useful level that I can work out.

2023-02-21 13:48 UTC, rowleya commented on SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/db/DbBasicTest.java
> +				assertThrows(TransientDataAccessResourceException.class,
But that is what it throws for better or worse.

2023-02-21 13:48 UTC, rowleya commented on SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/db/DbBasicTest.java
> +				assertThrows(DataIntegrityViolationException.class,
Apparently yes.  These are all passing tests.

2023-02-21 13:49 UTC, rowleya commented on SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/db/DbBasicTest.java
> +					() -> c.update(COUNT + "WHERE job_id = ?").call());
I don't really think adding checks on the string this version of MySQL happens to put in there is necessarily a good idea though.  I get what you mean, but so long as it gets an error, I think we can be happy it fails...

2023-02-21 13:50 UTC, rowleya commented on SpiNNaker-allocserv/pom.xml
> +		    <artifactId>testcontainers</artifactId>
If you install docker, it should "just work".  I didn't do anything more than that here, though admittedly on the Linux part of my Windows install.  Some details here of what is supported though:
https://www.testcontainers.org/supported_docker_environment/

2023-02-21 13:52 UTC, rowleya commented on SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/web/JobStateResponse.java
> +		return ui.getBaseUriBuilder().scheme(scheme).replacePath(servletPath)
I did put this back in as it helps with local testing quite a bit.  In general we deploy on https and there is no http access.  If we connect via http though, connecting via ws also makes sense...

2023-02-21 13:53 UTC, rowleya commented on SpiNNaker-allocserv/src/main/resources/application.yml
>    database-path: ${spalloc.working-directory}/spalloc.sqlite3
I think I left this hoping both might work, but now only mysql works, I have removed it again.

2023-02-21 13:54 UTC, rowleya commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/SpallocClientFactory.java
> -			conns.add(new ProxiedBootConnection(ws));
Yes, the Java code never brings up the boards, only the Python code ever does this.  We could add it back in if it changes...

2023-02-21 13:56 UTC, rowleya commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/SCPConnection.java
> +	public SCPConnection(HasChipLocation chip, InetAddress localHost,
All constructors are used by something, and all do something different...

2023-02-21 13:56 UTC, rowleya commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/connections/SCPConnection.java
> +	public SCPConnection(HasChipLocation chip, InetAddress localHost,
(i.e. there is now another constructor that has the same arguments)

2023-02-21 13:58 UTC, rowleya commented
Comments have generally been answered or updated.  Happy to accept further suggestions!  The query mentioned has been updated.  Note that Spring provides a connection pool for JDBCTemplate (HikariPool is used) automagically.

2023-02-23 11:04 UTC, dkfellows commented
Spring Boot pools for you? That's great.

2023-02-23 11:05 UTC, dkfellows commented on SpiNNaker-allocserv/pom.xml
> +		    <artifactId>testcontainers</artifactId>
It's to do with how this machine is set up.

2023-02-23 11:08 UTC, dkfellows commented on SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/db/DatabaseAPI.java
> +	interface RowMapper<T> {
Originally, those were made because they needed to propagate checked exceptions. I later put in mapping of those to unchecked exceptions, which meant that they could be converted to ordinary functional interfaces. I don't know if I went through and did that for all (and may have left some for the sake of making it clearer what is going on).

2023-02-23 11:10 UTC, dkfellows commented on SpiNNaker-allocserv/src/test/java/uk/ac/manchester/spinnaker/alloc/db/DbBasicTest.java
> +					() -> c.update(COUNT + "WHERE job_id = ?").call());
If it's the driver being goofy, we can't really fix that.

2023-02-23 11:19 UTC, dkfellows commented on SpiNNaker-allocserv/src/main/resources/queries/get_reported_boards.sql
> +	WHERE boards.functioning != 0 -- Ignore disabled boards
The NULL might have been some sort of initial state. I remember having to deal with it.

2023-02-23 11:22 UTC, dkfellows commented on SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/web/JobStateResponse.java
> +		return ui.getBaseUriBuilder().scheme(scheme).replacePath(servletPath)
The problem I had was with getting the system to choose https/wss despite the Tomcat instance actually being http/ws (because nginx was handling the certificate stuff).

2023-02-23 11:25 UTC, dkfellows commented
Summary: while there are changes that are arguable, the ones I really object to are the ones that mean we are binding the proxying to a single use case.

2023-02-23 13:18 UTC, rowleya commented on SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/web/JobStateResponse.java
> +		return ui.getBaseUriBuilder().scheme(scheme).replacePath(servletPath)
Ah you make a good point!  I will revert this then as it really isn't critical...

2023-02-23 13:22 UTC, rowleya commented
> Summary: while there are changes that are arguable, the ones I really object to are the ones that mean we are binding the proxying to a single use case.

Do you mean restoring the EIEIOConnection/BootConnection or something else?

2023-02-23 13:48 UTC, dkfellows commented
> Do you mean restoring the EIEIOConnection/BootConnection or something else?

That and the need to explicitly pass a `Machine` when that's only going to be used to generate information that was needed in the first place to create the connections; the map of what boards are in the allocation is already used internally (and that machine would just be to configure the connection selector). I want the API to be really simple.

2023-02-23 16:03 UTC, dkfellows commented
Thinking more about it, I don't mind allowing someone to pass a `Machine` to `job.getTransceiver()` if they have one, but I do mind requiring one to call it.

2023-02-23 16:04 UTC, rowleya commented
> Thinking more about it, I don't mind allowing someone to pass a `Machine` to `job.getTransceiver()` if they have one, but I do mind requiring one to call it.

Making it an optional arguments seems like a reasonable compromise.

2023-02-23 16:24 UTC, rowleya commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/SpallocClient.java
> -		EIEIOConnection getEIEIOConnection()
Actually, I remember now - the TransceiverInterface has a newEieioConnection, which *is* used.  The spalloc client one then seemed unnecessary since you get the TransceiverInterface from the client anyway.

2023-02-23 16:25 UTC, rowleya commented
> > Thinking more about it, I don't mind allowing someone to pass a `Machine` to `job.getTransceiver()` if they have one, but I do mind requiring one to call it.
> 
> Making it an optional arguments seems like a reasonable compromise.

This has been added in as a constructor without a machine (which ends up just calling the other, but the other now handles a null machine)

2023-02-23 16:32 UTC, rowleya commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/SpallocClientFactory.java
> -			conns.add(new ProxiedBootConnection(ws));
I have added this back in.  I think it was confusing during debugging to see it open the additional connection, but it doesn't do any harm having it.  It now also checks it exists in the connections and makes sure the right one is used.

2023-02-24 09:24 UTC, rowleya commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/SpallocClient.java
> +				uk.ac.manchester.spinnaker.machine.Machine machine)
OK, so in looking at refactoring this, the reason it was like this was because that is exactly how the transceiver itself works with the CommandLineInterface.  I have now refactored this quite a bit to get around the issue, but one outstanding issue (for a future PR) is that the proxy doesn't know the real machine dimensions in chips...

2023-02-24 15:24 UTC, dkfellows commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/SpallocClient.java
> -		EIEIOConnection getEIEIOConnection()
OK, using the transceiver to manufacture is fine. (It'd be up to the proxied transceiver to do anything special required there.)

2023-02-24 15:26 UTC, dkfellows approved these changes
There's things that are "not how I'd do them" but I'm not going to object to them for the sake of being awkward. 😁 Let's make this happen.

2023-02-24 15:52 UTC, merged