Remotespinnaker docker
SpiNNakerManchester/JavaSpiNNaker pull request #935
Opened 2023-07-10 13:10 UTC by rowleya

Adds docker to RemoteSpiNNaker

2023-07-24 08:17 UTC, dkfellows requested changes
A few small things, mostly relating to care when logging (because anything that originates outside the service might include `{}` in its string, confusing the logger's template engine).

The HTTP/HTTPS thing is *probably* just a testing vs deployment issue. I hope!

2023-07-24 08:17 UTC, dkfellows commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/SpallocClientFactory.java
> +			log.error("Error while reading json " + json);
`json` isn't fully trusted at this point; log it with:
```java
log.error("Error while reading json {}", json);
```

2023-07-24 08:17 UTC, dkfellows commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/SpallocClientFactory.java
> +			log.debug("Job URI = " + this.jobs);
Probably best to change this too.

2023-07-24 08:17 UTC, dkfellows commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/SpallocClientFactory.java
> +			this.jobs = asSecure(asDir(ri.jobsURI));
I wonder why the URI wasn't secure in the first place? Points to a different problem...

2023-07-24 08:17 UTC, dkfellows commented on SpiNNaker-comms/pom.xml
> +		    <artifactId>httpclient</artifactId>
Does the client use this dependency?

2023-07-24 08:20 UTC, rowleya commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/SpallocClientFactory.java
> +			this.jobs = asSecure(asDir(ri.jobsURI));
This is what the spalloc server returns.  Does this point to a configuration issue at the spalloc server?  It is running http internally but is behind an nginx https server...

2023-07-24 08:28 UTC, dkfellows commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/SpallocClientFactory.java
> +			this.jobs = asSecure(asDir(ri.jobsURI));
It's *supposed* to trust the proxying headers put in by nginx (that's something that has to be enabled in config IIRC, which is fair enough).

2023-07-24 08:53 UTC, rowleya commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/SpallocClientFactory.java
> +			this.jobs = asSecure(asDir(ri.jobsURI));
Ah yes, that was the issue - the URLs are now https after changing the nginx config on spalloc.  Maybe then this shouldn't be done...

2023-07-25 12:03 UTC, dkfellows commented
How does this relate to #934?

2023-07-25 12:04 UTC, dkfellows commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/SpallocClientFactory.java
> +			this.jobs = asSecure(asDir(ri.jobsURI));
It's always best to ensure that URLs are correct to start out with instead of munging them client-side.

2023-07-25 12:28 UTC, rowleya commented
They are mostly the same, but this one is an extension of that one.  Given you have reviewed this one I will probably delete that one...

2023-07-26 09:33 UTC, rowleya commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/SpallocClientFactory.java
> +			log.error("Error while reading json " + json);
Fixed

2023-07-26 09:33 UTC, rowleya commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/SpallocClientFactory.java
> +			log.debug("Job URI = " + this.jobs);
Removed altogether as part of something else

2023-07-26 09:33 UTC, rowleya commented on SpiNNaker-comms/src/main/java/uk/ac/manchester/spinnaker/alloc/client/SpallocClientFactory.java
> +			this.jobs = asSecure(asDir(ri.jobsURI));
Removed now

2023-07-26 09:33 UTC, rowleya commented on SpiNNaker-comms/pom.xml
> +		    <artifactId>httpclient</artifactId>
Once the asSecure code is removed this is no longer used

2023-07-29 15:41 UTC, dkfellows approved these changes

2023-07-31 06:52 UTC, merged