Fix the notification of compat jobs
SpiNNakerManchester/JavaSpiNNaker pull request #992
Opened 2023-08-11 15:42 UTC by rowleya

2023-08-14 10:13 UTC, dkfellows commented
Not working yet... 😕

2023-08-17 14:07 UTC, dkfellows commented
You might need to do significant work on this branch after #994.

2023-09-04 08:33 UTC, rowleya commented
This now appears to work correctly.

2023-09-04 08:50 UTC, dkfellows requested changes

2023-09-04 08:50 UTC, dkfellows commented on SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/bmp/BMPController.java
> +		sched.initialize();
There's already a call to that, later in the method and _after_ the pool size has been set. I think this call is unnecessary.

2023-09-04 08:50 UTC, dkfellows commented on SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/Epochs.java
> +		return map.get(id);
I've been wondering whether this set should be copied so that the references become strong ones...

Something for another PR I believe.

2023-09-04 09:05 UTC, dkfellows commented on SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/allocator/Epochs.java
> +		return map.get(id);
See #1028

2023-09-04 10:12 UTC, rowleya commented on SpiNNaker-allocserv/src/main/java/uk/ac/manchester/spinnaker/alloc/bmp/BMPController.java
> +		sched.initialize();
That's what I thought too, but it turns out that makeWorkers was calling the scheduler before it was initialised then.  I have reordered the calls and this appears to fix things and not call initialize twice.

2023-09-04 14:30 UTC, dkfellows approved these changes

2023-09-04 14:40 UTC, merged